services:
  postgres:
    image: postgres:18.0
    restart: always
    ports:
      - "5432:5432"
    deploy:
      mode: "replicated"
      replicas: 1
    environment:
      POSTGRES_USER: catalog_db
      POSTGRES_PASSWORD: catalog_db_password
      POSTGRES_DB: catalog_service
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

volumes:
  postgres_data: