services:
  catalog_db_server:
    image: postgres:18.0
    restart: always
    ports:
      - "5432:5432"
    deploy:
      mode: "replicated"
      replicas: 1
    environment:
      POSTGRES_USER: catalog_db
      POSTGRES_PASSWORD: catalog_db_password
      POSTGRES_DB: catalog_service
    volumes:
      - "catalog_db_server:/var/lib/postgresql/data"
  order_db_server:
    image: postgres:18.0
    restart: always
    ports:
      - "5433:5432"
    deploy:
      mode: "replicated"
      replicas: 1
    environment:
      POSTGRES_USER: order_db
      POSTGRES_PASSWORD: order_db_password
      POSTGRES_DB: order_service
    volumes:
      - "order_db_server:/var/lib/postgresql/data"
  user_db_server:
    image: postgres:18.0
    restart: always
    ports:
      - "5442:5432"
    deploy:
      mode: "replicated"
      replicas: 1
    environment:
      POSTGRES_USER: user_db
      POSTGRES_PASSWORD: user_db_password
      POSTGRES_DB: user_service
    volumes:
      - "user_db_server:/var/lib/postgresql/data"

volumes:
  catalog_db_server:
  order_db_server:
  user_db_server: